name: Container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    steps: #dockerコンテナ内でステップを実行
      - uses: actions/checkout@v2
      - name: Log node version
        run: |
          cat /etc/os-release #Linuxバージョンの確認
          pwd
          ls -la
          nproc
          free -m
  docker-compose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: compose
        run: |
          ls -la
          docker compose run --rm app
          docker image ls
  docker-compose2:
    needs: docker-compose
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: compose
        run: |
          ls -la
          docker compose run --rm self
          docker image ls