name: Container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    steps: #dockerコンテナ内でステップを実行
      - uses: actions/checkout@v2
      - name: Log node version
        run: |
          cat /etc/os-release #Linuxバージョンの確認
          pwd
          ls -la
          nproc
          free -m
  docker-compose:
    needs: node-docker
    runs-on: ubuntu-latest
    steps:
      - name: compose
        run: |
          ls -la