name: learn-github-actions
on: [fork]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - run: echo "this is pen"
      - run: |
          ls -la
          pwd
          touch b
          ls -la